### ISSUE TITLE
關於中國服更新資料

### ISSUE THREAD

**Issue by timchen0607** [thewakingsands/ffxiv-datamining-cn#1]
您好 無意間翻到此專案
感謝提供解包後的檔案
想另外詢問能否順道更新解包前的檔案呢?
0a0000.win32.dat0 與 0a0000.win32.index

**Comment by timchen0607** [comment]
您好 我看到更新了 6.0 的資料
請問中國服已經有更新的檔案了嗎?
如果方便能分享 6.0 的檔案嗎，謝謝您。

**Comment by oott123** [comment]
@timchen0607 是的。下载地址在： https://ff.web.sdo.com/web8/index.html#/newstab/newscont/337516
