### ISSUE TITLE
关于无人岛所有可采集物的坐标

### ISSUE THREAD

**Issue by MisakaCirno** [thewakingsands/ffxiv-datamining-cn#2]
在无人岛里选中这些可采集物会显示它们的名字，我以其中的一个“熟透的高山萝卜”作为例子，找到了EObjName.csv，这个应该是一个可拾取物品的ID与名称的映射表。

得到了“熟透的高山萝卜”的Key是“2013182”。

然后利用“2013182”找到了EObj.csv，应该是全部的可采集物和一些其他的信息。

还找到了MJIGatheringObject.csv，这个里面应该是在无人岛里所有可拾取的物品。

根据这个名字又找到了MJIGatheringItem.csv，这个给出了坐标，但看样子像是手册上那个范围，而不是具体坐标。

MJIGathering.csv里应该是所有可拾取物品了，但是没有具体的在地图上的坐标。它们的ID也没办法作为特征找到在哪个表里用到了。

这些数据里面会有具体坐标的数据吗，我好像也没看到有人做了把所有的坐标展示在某个地图上这样的工具。

**Comment by oott123** [comment]
可以探索 Layer 表，不过不用对此报太多希望，有可能是服务端来的。

**Comment by MisakaCirno** [comment]
> 可以探索 Layer 表，不过不用对此报太多希望，有可能是服务端来的。

礼问一下Layer表具体指的是哪个表呢？以Layer为关键字查出来的表似乎内容都没有很大的关系。

**Comment by oott123** [comment]
讲错了，是 Level

https://github.com/thewakingsands/ffxiv-datamining-cn/blob/master/Level.csv

**Comment by MisakaCirno** [comment]
> 讲错了，是 Level
> 
> https://github.com/thewakingsands/ffxiv-datamining-cn/blob/master/Level.csv

感谢指路，做了一下筛查发现这里面主要是存了一些交互道具的坐标，例如木板、NPC、指定地点等，没有采集的具体坐标。看来真的有可能是服务端来的，我准备到时候抓包检查一下看看。
